name: Test, build, and publish Docker images

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
      - secondary
  pull_request:

jobs:
  # ===========================================================================
  # Test Docker images
  # ===========================================================================
  docker_test:
    name: Test the docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      # Dockerfile
      - name: Build Dockerfile
        run: |
          docker build -t reuse .
      # - name: Run Docker image
      #   run: |
      #     docker run -v "$(pwd):/data" reuse
      # Dockerfile-debian
      - name: Build Dockerfile-debian
        run: |
          docker build -t reuse-debian --file Dockerfile-debian .
      # - name: Run Docker debian image
      #   run: |
      #     docker run -v "$(pwd):/data" reuse-debian

  # ===========================================================================
  # Build and push Docker images for tagged releases
  # ===========================================================================
  docker_push_tag:
    name: Push Docker image for tags to Docker Hub
    runs-on: ubuntu-latest
    # Depends on successful Docker build/test
    needs:
      - docker_test
    if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Dockerfile
      - name: Default Docker - set metadata
        id: meta_default
        uses: docker/metadata-action@v3
        with:
          images: mxmehl/docker-ci-test
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
      - name: Default Docker - build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_default.outputs.tags }}
          labels: ${{ steps.meta_default.outputs.labels }}

      # Dockerfile-debian
      - name: Debian Docker - set metadata
        id: meta_debian
        uses: docker/metadata-action@v3
        with:
          images: mxmehl/docker-ci-test
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
          flavor: |
            suffix=-debian,onlatest=true
      - name: Debian Docker - build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_debian.outputs.tags }}
          labels: ${{ steps.meta_debian.outputs.labels }}

  # ===========================================================================
  # Build and push Docker images for main branch updated (dev tag)
  # ===========================================================================
  docker_push_dev:
    name: Push Docker image for main branch to Docker Hub
    runs-on: ubuntu-latest
    # Depends on successful Docker build/test
    needs:
      - docker_test
    if: ${{ github.event_name != 'pull_request' && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/secondary' ) }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Dockerfile
      - name: Default Docker - set metadata
        id: meta_default
        uses: docker/metadata-action@v3
        with:
          images: mxmehl/docker-ci-test
          tags: |
            type=raw,value=dev
      - name: Default Docker - build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_default.outputs.tags }}
          labels: ${{ steps.meta_default.outputs.labels }}

      # Dockerfile-debian
      - name: Debian Docker - set metadata
        id: meta_debian
        uses: docker/metadata-action@v3
        with:
          images: mxmehl/docker-ci-test
          tags: |
            type=raw,value=dev-debian
      - name: Debian Docker - build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_debian.outputs.tags }}
          labels: ${{ steps.meta_debian.outputs.labels }}
