name: Test, build, and publish Docker images

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
  pull_request:

jobs:
  docker_test:
    name: Test the docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build Dockerfile
        run: |
          docker build -t reuse .
      # - name: Run Docker image
      #   run: |
      #     docker run -v "$(pwd):/data" reuse
      - name: Build Dockerfile-debian
        run: |
          docker build -t reuse-debian --file Dockerfile-debian .
      # - name: Run Docker debian image
      #   run: |
      #     docker run -v "$(pwd):/data" reuse-debian

  docker_push_tag:
    name: Push Docker image for tagged release to Docker Hub
    runs-on: ubuntu-latest
    # Depends on successful Docker build/test
    needs: docker_test
    if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for default Docker image
        id: meta_default
        uses: docker/metadata-action@v3
        with:
          images: mxmehl/docker-ci-test
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: Extract metadata (tags, labels) for Debian Docker image
        id: meta_debian
        uses: docker/metadata-action@v3
        with:
          images: mxmehl/docker-ci-test
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
          flavor: |
            suffix=-debian,onlatest=true

      - name: Build and push default Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta_default.outputs.tags }}
          labels: ${{ steps.meta_default.outputs.labels }}

      - name: Build and push Debian Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile-debian
          push: true
          tags: ${{ steps.meta_debian.outputs.tags }}
          labels: ${{ steps.meta_debian.outputs.labels }}

  docker_push_dev:
    name: Push Docker dev image to Docker Hub
    runs-on: ubuntu-latest
    # Depends on successful Docker build/test
    needs: docker_test
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for default Docker
        id: meta_default
        uses: docker/metadata-action@v3
        with:
          images: mxmehl/docker-ci-test
          tags: |
            type=raw,value=dev

      - name: Extract metadata (tags, labels) for Debian Docker
        id: meta_debian
        uses: docker/metadata-action@v3
        with:
          images: mxmehl/docker-ci-test
          tags: |
            type=raw,value=dev-debian

      - name: Build and push default Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta_default.outputs.tags }}
          labels: ${{ steps.meta_default.outputs.labels }}

      - name: Build and push Debian Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile-debian
          push: true
          tags: ${{ steps.meta_debian.outputs.tags }}
          labels: ${{ steps.meta_debian.outputs.labels }}
